name = "Korok"
author = "Hedwig"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a19f96a98d4929d39984360fd38f68bdaef7a1b1c928b58f5470d5f7e8c75cb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = []
