name = "Korok"
author = "Hedwig"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "417b3225e5b504c9aaf5c244a6f815703643a406a03af9da84a6aad82a5c839a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = []
