name = "Korok"
author = "Hedwig"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5df3cf653a795c573b5f55557ad4c4a5e375abd426dac6f30480a7af2a38dbd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = []
